server:
  port: 3007

spring:
  application:
    name: ai-service
  config:
    import:
      - 'optional:configserver:'
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

  ai:
    chat:
      client:
        enabled: false
    vertex.ai.gemini:
      projectId: ${GOOGLE_CLOUD_PROJECT_ID}
      location: us-west1
      chat:
        options:
          model: gemini-2.0-flash
          temperature: 0.4

eureka:
  instance:
    prefer-ip-address: false
    hostname: code-factory.co.kr

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:3150/eureka/